apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-demo-service
  labels:
    app: flask-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: flask-k8s-demo
  ports:
    - name: http
      port: 80
      targetPort: 5000
